version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  node/test:
    executor:
      name: node/default
    steps:
      - run: npm install
      - run: npm t
workflows:
  test:
    jobs:
      - node/test:
          version: '16.10'
          pkg-manager: npm
